### ISSUE TITLE
Verification logs don't seem to work

### ISSUE THREAD

**Issue by OIRNOIR** [astridlol/Keycard#6]
I've verified that the bot has permission to view and send messages in the channel, then I set the channel as the log channel, then I had a bunch of people verify, but no log messages appear.

**Comment by kyle95wm** [comment]
Sounds like a skill issue. They work fine in my server.

**Comment by OIRNOIR** [comment]
> Sounds like a skill issue. They work fine in my server.

That's odd. What permissions do logs seem to require?

**Comment by OIRNOIR** [comment]
Nevermind, it was a permissions issue. Facepalm.
